Adds setup for simple benchmarks
bitExpert/disco pull request #80
Opened 2016-12-07 15:36 UTC by jaapio

These changes add a simple benchmark setup.
This allows us to create and run the benchmark tests.

2016-12-07 16:24 UTC, jaapio commented
I started with this small setup. Let me know if there are features that I didn't cover

2016-12-07 20:38 UTC, shochdoerfer requested changes
For an initial version it looks good, see my remarks for some minor changes. In addition to that I would love to see benchmarks for the different bean configuration options (singleton / non-singleton, lazy / non-lazy, alias) to see which impact the different configuration options have.

Do you have a good idea how to add the benchmarks to the README.md file? Since we have the "production tuning" section there it might be a good idea to include the benchmark results there somehow.

2016-12-07 20:38 UTC, shochdoerfer commented on benchmarks/Asset/MyConfiguration.php
> +    public function mySimpleService() : A {
For consistency reasons the method should be named A. You could define "mySimpleService" as alias. That way we could also run a bechmark trying to retrieve beans by the alias.

2016-12-07 20:38 UTC, shochdoerfer commented on benchmarks/Asset/MyConfiguration.php
> +    public function B() : B {
Please use the PSR-2 standard for formatting the configuration class.

2016-12-07 20:38 UTC, shochdoerfer commented on benchmarks/Asset/MyConfiguration.php
> +class MyConfiguration
Better rename the class to BenchmarkConfiguration so that it is clear what the purpose of the class is.

2016-12-07 20:38 UTC, shochdoerfer commented on benchmarks/Bench/ObjectCreationOptimizedConfig.php
> +    public function benchCreateInstance()
For consistency reasons the method should be named benchCreateSimple()

2016-12-07 20:43 UTC, jaapio commented
phpbench supports reporting to markdown, so it will be very easy to add those results to the readme.

I will have a look at your requested changes and add more benchmarks for other cases. Glad you like the initial setup.

2016-12-08 10:25 UTC, jaapio commented on benchmarks/Bench/BaseObjectCreation.php
> +        $this->disco->get('mySimpleService');
For some reason this bench will run forever.

2016-12-11 12:43 UTC, shochdoerfer commented on benchmarks/Bench/BaseObjectCreation.php
> +        $this->disco->get('mySimpleService');
Seems to work fine for me. Which PHP version did you use to run the test?

2016-12-11 12:48 UTC, jaapio commented
I used php7.0 not sure about the exact version

Op zo 11 dec. 2016 13:43 schreef Stephan Hochdörfer <
notifications@github.com>:

> *@shochdoerfer* commented on this pull request.
> ------------------------------
>
> In benchmarks/Bench/BaseObjectCreation.php
> <https://github.com/bitExpert/disco/pull/80>:
>
> > +
> +use bitExpert\Disco\BeanFactory;
> +
> +abstract class BaseObjectCreation
> +{
> +    /** @var BeanFactory */
> +    protected $disco;
> +
> +    public function benchCreateSimple()
> +    {
> +        $this->disco->get('A');
> +    }
> +
> +    public function benchCreateSimpleAliased()
> +    {
> +        $this->disco->get('mySimpleService');
>
> Seems to work fine for me. Which PHP version did you use to run the test?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitExpert/disco/pull/80>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABAuUXfAf4vhJXrCqaQAh936vVdTFw3qks5rG_AMgaJpZM4LGu4R>
> .
>

2016-12-11 18:02 UTC, merged