[WIP] Add a Contributing Guide
bitExpert/disco pull request #87
Opened 2017-01-29 06:59 UTC by settermjd

This PR:

- adds instructions showing how to contribute to the project.

:information_desk_person: As part of the overhaul of the documentation, I want to make it as easy as possible for others to know how to contribute to the project.

2017-01-29 07:00 UTC, settermjd commented
@shochdoerfer, this is still a work-in-progress, as there's a bit of extra information still required. But should be finished relatively quickly.

2017-01-29 09:23 UTC, shochdoerfer commented
Good starting point! For the ci tasks we have some phing tasks which you should refer to in the documentation:
 - To run CodeSniffer use: ./vendor/bin/phing sniff 
 - To run PHPUnit use: ./vendor/bin/phing unit 
 - To lint the PHP code use: ./vendor/bin/phing lint

Before sending a PR one should run `composer.phar validate` as the Travis build will also run the command and will fail if the composer.lock file is not up-to-date with the changes in the composer.json file.

2017-01-29 14:50 UTC, settermjd commented
Ok, the initial draft's now done and it's ready for review.

2017-01-29 20:40 UTC, shochdoerfer requested changes

2017-01-29 20:40 UTC, shochdoerfer commented on CONTRIBUTING.md
> +For sensitive email communications, please use [our PGP key](http://pgp.mit.edu/pks/lookup?op=vindex&search=0xEC37D631657E0A89).
I generated a PGP key for the opensource@bitExpert.de email address, please use [this](http://pgp.mit.edu/pks/lookup?op=vindex&search=0x6DE7F8597CECDF13) link as reference.

2017-01-29 20:40 UTC, shochdoerfer commented on CONTRIBUTING.md
> +$ curl -sS https://getcomposer.org/installer | php --
Not sure if it makes sense to better refer to the Composer documentation on how to [install Composer](https://getcomposer.org/download/) as their docs mention the more "secure" method.

2017-01-29 20:40 UTC, shochdoerfer commented on CONTRIBUTING.md
> +Before sending a PR, run `composer.phar validate`, as the Travis build will also run the command and will fail if the composer.lock file is not up-to-date with the changes in the composer.json file.
It should be mentioned that the CodeSniffer tests as well the PHPUnit tests need also to run.

2017-01-30 10:03 UTC, settermjd commented on CONTRIBUTING.md
> +$ curl -sS https://getcomposer.org/installer | php --
Sounds good to me.

2017-01-30 10:04 UTC, settermjd commented on CONTRIBUTING.md
> +Before sending a PR, run `composer.phar validate`, as the Travis build will also run the command and will fail if the composer.lock file is not up-to-date with the changes in the composer.json file.
Shall do. Thanks for the pointers while I'm still getting up to speed with the project.

2017-01-31 16:46 UTC, shochdoerfer commented
@settermjd Could you apply the few changes I mentioned above so that I can merge the PR?

2017-01-31 16:55 UTC, settermjd commented
@shochdoerfer done!

2017-01-31 16:59 UTC, merged

2017-01-31 16:59 UTC, shochdoerfer commented
Thank you @settermjd for your first Disco PR!

2017-02-01 04:51 UTC, settermjd commented
Not a problem at all. Here's to many more!